#!/usr/bin/env bash
# Regenerate app/judge/static/tailwind.css (the vendored Judge UI stylesheet).
#
# The Judge page used to pull https://cdn.tailwindcss.com at runtime plus two
# Google Fonts stylesheets. That made the demo depend on a third party being
# reachable, execute an unpinned remote script, and break entirely offline.
# The generated CSS is committed instead, so a clean clone is self-contained.
#
# Requirements: node >= 18 and network access ONCE, to fetch the pinned
# Tailwind CLI. The output is committed, so judges never need this script.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TAILWIND_VERSION="3.4.17"
BUILD_DIR="$(mktemp -d)"
trap 'rm -rf "$BUILD_DIR"' EXIT

cat >"$BUILD_DIR/input.css" <<'CSS'
@tailwind base;
@tailwind components;
@tailwind utilities;
CSS

cat >"$BUILD_DIR/tailwind.config.js" <<CONFIG
// System font stacks only: the Judge UI must not fetch webfonts.
module.exports = {
  content: ["$ROOT/app/judge/render.py"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "Helvetica", "Arial", "sans-serif"],
        mono: ["ui-monospace", "SFMono-Regular", "Menlo", "Consolas", "monospace"],
      },
    },
  },
};
CONFIG

echo "Building Judge UI CSS with tailwindcss@$TAILWIND_VERSION ..."
npx --yes "tailwindcss@$TAILWIND_VERSION" build \
  -c "$BUILD_DIR/tailwind.config.js" \
  -i "$BUILD_DIR/input.css" \
  -o "$BUILD_DIR/out.css" \
  --minify 2>/dev/null

OUT="$ROOT/app/judge/static/tailwind.css"
{
  printf '%s\n' \
    '/*' \
    ' * WIENER Judge UI stylesheet (vendored, offline-capable).' \
    ' *' \
    ' * Generated by Tailwind CSS v'"$TAILWIND_VERSION"' from the class names in' \
    ' * app/judge/render.py. This file is COMMITTED so a clean clone renders the' \
    ' * Judge UI with no network access and no third-party script execution.' \
    ' *' \
    ' * Regenerate with:' \
    ' *   ./scripts/build_judge_css.sh' \
    ' *' \
    ' * Do not hand-edit. Font stacks are system-only on purpose: no Google Fonts,' \
    ' * no webfont, no CDN script.' \
    ' */'
  cat "$BUILD_DIR/out.css"
  printf '\n'
} >"$OUT"

echo "Wrote $OUT ($(wc -c <"$OUT") bytes)"
